Update 16_rootaccess

diff --git a/scripts/16_rootaccess b/scripts/16_rootaccess
--- a/scripts/16_rootaccess
+++ b/scripts/16_rootaccess
@@ -1,9 +1,9 @@
 function f_rootaccess {
   echo "[$SCRIPT_COUNT] root access"
 
-  if ! grep -E '^+\s:\sroot\s:\s127.0.0.1$|^:root:127.0.0.1' "$SECURITYACCESS"; then
-    sed -i 's/^#.*root.*:.*127.0.0.1$/+:root:127.0.0.1/' "$SECURITYACCESS"
-  fi
+  #if ! grep -E '^+\s:\sroot\s:\s127.0.0.1$|^:root:127.0.0.1' "$SECURITYACCESS"; then
+  #  sed -i 's/^#.*root.*:.*127.0.0.1$/+:root:127.0.0.1/' "$SECURITYACCESS"
+  #fi
 
   echo "console" > /etc/securetty
 
@@ -24,9 +24,9 @@ function f_rootaccess {
 
   ((SCRIPT_COUNT++))
 
-  echo "[$SCRIPT_COUNT] Restrict access to su"
+  #echo "[$SCRIPT_COUNT] Restrict access to su"
 
-  if ! grep -q 'auth required' /etc/pam.d/su; then
-    echo "auth required pam_wheel.so" > /etc/pam.d/su
-  fi
+  #if ! grep -q 'auth required' /etc/pam.d/su; then
+  #  echo "auth required pam_wheel.so" > /etc/pam.d/su
+  #fi
 }
