For ubuntu-22.04 the script to delete users was not working so, version check added

diff --git a/scripts/users b/scripts/users
--- a/scripts/users
+++ b/scripts/users
@@ -1,9 +1,41 @@
+#!/bin/bash
+
+SCRIPT_COUNT=1
+
 function f_users {
   echo "[$SCRIPT_COUNT] Remove users"
 
-  for users in games gnats irc list news sync uucp; do
-    userdel -r "$users" 2> /dev/null
+  for user in games gnats irc list news sync uucp; do
+    sudo userdel -r "$user" 2> /dev/null
   done
 
   ((SCRIPT_COUNT++))
 }
+
+function f_users_modified {
+  echo "[$SCRIPT_COUNT] Remove users"
+
+  for user in games gnats irc list news sync uucp; do
+    if id "$user" &>/dev/null; then
+      sudo pkill -u "$user"
+      sudo userdel -r "$user" 2>/dev/null
+
+      if [ $? -eq 0 ]; then
+        echo "User $user deleted successfully."
+      else
+        echo "Failed to delete user $user."
+      fi
+    else
+      echo "User $user does not exist."
+    fi
+  done
+
+  ((SCRIPT_COUNT++))
+}
+
+# Check Ubuntu version
+if lsb_release -d | grep -q "Ubuntu 22.04"; then
+  f_users_modified
+else
+  f_users
+fi
